{
 "title": "Project Overview",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_id",
    "label": "Project ID",
    "query": "SELECT DISTINCT project_id FROM gitlab_ci.pipelines"
   }
  ]
 },
 "panels": [
  {
   "title": "Pipelines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(count(id)) OVER (ORDER BY interval ASC)\nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id} AND $__timeFilter(finished_at)\nGROUP BY $__timeInterval(finished_at) as interval\nORDER BY interval",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(count(id)) OVER (ORDER BY interval ASC)\nFROM gitlab_ci.jobs\nWHERE pipeline.project_id = ${project_id} AND $__timeFilter(finished_at)\nGROUP BY $__timeInterval(finished_at) as interval\nORDER BY interval",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Sections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(count(id)) OVER (ORDER BY interval ASC)\nFROM gitlab_ci.sections\nWHERE pipeline.project_id = ${project_id} AND $__timeFilter(finished_at)\nGROUP BY $__timeInterval(finished_at) as interval\nORDER BY interval",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Test Cases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(count(testcases.id)) OVER (ORDER BY interval ASC)\nFROM gitlab_ci.testcases AS testcases\n  INNER JOIN gitlab_ci.pipelines AS pipelines ON testcases.testreport.pipeline_id = pipelines.id\nWHERE (pipelines.project_id = ${project_id}) AND $__timeFilter(pipelines.finished_at)\nGROUP BY $__timeInterval(finished_at) AS interval\nORDER BY interval",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Pipeline Success Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(status) AS success_count,\n  ( SELECT count() FROM gitlab_ci.pipelines WHERE project_id = ${project_id} AND $__timeFilter(finished_at) ) AS total_count \n  FROM gitlab_ci.pipelines\n  WHERE project_id = ${project_id} AND status = 'success' AND $__timeFilter(finished_at)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Job Success Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(status) AS success_count,\n  ( SELECT count() FROM gitlab_ci.jobs WHERE pipeline.project_id = ${project_id} AND $__timeFilter(finished_at)) AS total_count \n  FROM gitlab_ci.jobs\n  WHERE pipeline.project_id = ${project_id} AND status = 'success' AND $__timeFilter(finished_at)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Test Success Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(testsuites.success_count) / sum(testsuites.total_count - testsuites.skipped_count) AS success_ratio\nFROM gitlab_ci.testsuites AS testsuites\n  INNER JOIN gitlab_ci.pipelines AS pipelines ON testsuites.testreport.pipeline_id = pipelines.id\nWHERE\n  pipelines.project_id = '${project_id}' AND $__timeFilter(pipelines.finished_at)\nGROUP BY toStartOfHour(toDateTime64(pipelines.finished_at, 3)) AS time\nORDER BY time",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Pipeline Runs per $__interval",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(finished_at) as time, status, count()\n  FROM gitlab_ci.pipelines \n  WHERE (project_id = '${project_id}') AND $__timeFilter(time)\n  GROUP BY status, time\n  ORDER BY time ASC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Job Runs per $__interval",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(finished_at) as time, status, count()\n  FROM gitlab_ci.jobs \n  WHERE (pipeline.project_id = '${project_id}') AND $__timeFilter(time)\n  GROUP BY status, time\n  ORDER BY time ASC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Pipelines Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT status, count(status)\nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id} AND $__timeFilter(finished_at)\nGROUP BY status",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Pipelines",
   "type": "table",
   "gridPos": { "h": 18, "w": 17, "x": 7, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT id, toDateTime64(finished_at, 3) AS finished_at, status, source, ref, queued_duration, duration\nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id} AND $__timeFilter(finished_at)\n",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Jobs Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT status, count(status)\nFROM gitlab_ci.jobs \nWHERE pipeline.project_id = ${project_id} AND $__timeFilter(finished_at)\nGROUP BY status",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Top 5 Jobs by Duration",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  regexpExtract(name, '(.+)\\\\s+\\\\[.+\\\\]', 1) AS name,\n  avg(duration) AS avg_duration,\n  max(duration) AS max_duration\nFROM gitlab_ci.jobs\nWHERE pipeline.project_id = ${project_id}\n  AND $__timeFilter(finished_at)\n  AND name != ''\nGROUP BY name\nORDER BY avg_duration DESC\nLIMIT 5",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Pipeline Durations",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toDateTime64(finished_at, 3) AS time,\n  duration\nFROM gitlab_ci.pipelines\nWHERE project_id = ${project_id} AND status = 'success' AND $__timeFilter(finished_at)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Job Durations",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toDateTime64(finished_at, 3) AS time,\n  duration,\n  name\nFROM gitlab_ci.jobs\nWHERE pipeline.project_id = ${project_id} AND status = 'success' AND $__timeFilter(finished_at)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Test Reports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Test Cases",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  testcases.status, count(testcases.status)\nFROM gitlab_ci.testcases AS testcases\n  INNER JOIN gitlab_ci.pipelines AS pipelines ON testcases.testreport.pipeline_id = pipelines.id\nWHERE\n  pipelines.project_id = ${project_id} AND $__timeFilter(pipelines.finished_at)\nGROUP BY testcases.status\n",
       "selectedFormat": 1
      }
     ]
    },
    {
     "title": "Test Result Trend and Pass Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 17, "x": 7, "y": 51 },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  sum(testsuites.failed_count + testsuites.error_count) AS failure_count,\n  sum(testsuites.success_count) / sum(testsuites.total_count - testsuites.skipped_count) AS success_ratio\nFROM gitlab_ci.testsuites AS testsuites\n  INNER JOIN gitlab_ci.pipelines AS pipelines ON testsuites.testreport.pipeline_id = pipelines.id\nWHERE\n  pipelines.project_id = '${project_id}' AND $__timeFilter(pipelines.finished_at)\nGROUP BY toStartOfDay(toDateTime64(pipelines.finished_at, 3)) AS time\nORDER BY time DESC",
       "selectedFormat": 4
      }
     ]
    },
    {
     "title": "Top 10 Test Cases by Failure Count",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "rawSql": "SELECT\n  name, classname, count() AS failed_count, avg(execution_time) AS avg_execution_time\nFROM gitlab_ci.testcases AS testcases\n  INNER JOIN gitlab_ci.pipelines AS pipelines ON testcases.testreport.pipeline_id = pipelines.id\nWHERE testcases.status IN ('failed', 'error')\n  AND pipelines.project_id = ${project_id}\n  AND $__timeFilter(pipelines.finished_at)\nGROUP BY name, classname\nORDER BY failed_count DESC, avg_execution_time DESC\nLIMIT 10",
       "selectedFormat": 4
      }
     ]
    }
   ]
  }
 ]
}