stages:
  - lint
  - build
  - test
  - release

variables:
  GIT_DEPTH: 0

  CACHE_DIR: ${CI_PROJECT_DIR}/.cache
  GOPATH: ${CI_PROJECT_DIR}/.go
  GOCACHE: ${CACHE_DIR}/go-build
  GOMAXPROCS: "8"
  GOVERSION: "1.24"

  RUNNER_TAG: "self-hosted"

workflow:
  rules:
    - if: $CI_COMMIT_TAG != null
      variables:
        RUNNER_TAG: saas-linux-small-amd64
    - when: always

default:
  tags: [ $RUNNER_TAG ]
  image: golang:${GOVERSION}
  hooks:
    pre_get_sources_script:
      - | # Print some job properties
        printf 'PROPERTY_%s="%s"\n' "ci_runner_id" "${CI_RUNNER_ID}"
        printf 'PROPERTY_%s="%s"\n' "ci_runner_version" "${CI_RUNNER_VERSION}"
        printf 'PROPERTY_%s="%s"\n' "ci_runner_revision" "${CI_RUNNER_REVISION}"
        printf 'PROPERTY_%s="%s"\n' "ci_runner_hostname" "${HOSTNAME}"

.cache: &cache-defaults
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${CACHE_DIR}
    - ${GOPATH}
  policy: pull-push

lint:
  stage: lint
  cache:
    - <<: *cache-defaults
  variables:
    GOLANGCI_LINT_VERSION: v2.6.2
    GOLANGCI_LINT_CACHE: ${CACHE_DIR}/golangci-lint
  before_script:
    - |
      # Print some job properties
      printf 'PROPERTY_%s="%s"\n' "golangci_lint_version" "${GOLANGCI_LINT_VERSION}"
    - |
      # Download golangci-lint binary
      echo -e "\e[0Ksection_start:$(date +%s):script_step_before\r\e[0KRunning script_step_before"
      curl -sSfL https://github.com/golangci/golangci-lint/releases/download/${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION#v}-linux-amd64.tar.gz -o /tmp/golangci-lint.tar.gz
      mkdir -p ${GOPATH}/bin
      tar -C ${GOPATH}/bin/ -zxof /tmp/golangci-lint.tar.gz --strip-components=1 golangci-lint-${GOLANGCI_LINT_VERSION#v}-linux-amd64/golangci-lint
      export PATH=${GOPATH}/bin:$PATH
      echo -e "\e[0Ksection_end:$(date +%s):script_step_before\r\e[0K"
  script:
    - make lint
  allow_failure: true

build:
  stage: build
  cache:
    - <<: *cache-defaults
  script:
    - make build-all platform=linux/amd64,linux/arm64
  artifacts:
    paths:
      - bin

build-image:
  stage: build
  needs:
    - build
  image:
    name: docker.io/moby/buildkit:rootless
    entrypoint: ["sh", "-c"]
  parallel:
    matrix:
      - APP:
          - gitlab-exporter
          - gitlab-exporter-clickhouse-recorder
  variables:
    IMAGE: gitlab-exporter/$APP
    VERSION: $CI_COMMIT_SHA
    PLATFORM: linux/amd64,linux/arm64

    BUILDKIT_IMAGE: "$CI_REGISTRY/$IMAGE:$VERSION"
    BUILDKIT_PUSH: "false"

    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script:
    - mkdir ~/.docker
    - |
      echo "{
        \"auths\": {
          \"${CI_REGISTRY}\": {
            \"auth\": \"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"
          }
        }
      }" > ~/.docker/config.json
  script:
    - |
      buildctl-daemonless.sh build \
        --trace ${CI_PROJECT_DIR}/buildctl-trace.json \
        --frontend dockerfile.v0 \
        --local dockerfile="${CI_PROJECT_DIR}" \
        --local context="${CI_PROJECT_DIR}/bin" \
        --opt platform="${PLATFORM}" \
        --opt build-arg:APP="${APP}" \
        --output type=image,\"name=${BUILDKIT_IMAGE}\",push=${BUILDKIT_PUSH}
  artifacts:
    paths:
      - buildctl-trace.json
    when: always

build-chart:
  stage: build
  needs:
    - job: build-image
      artifacts: false
  image: quay.io/helmpack/chart-testing:v3.12.0
  parallel:
    matrix:
      - APP:
          - gitlab-exporter
          - gitlab-exporter-clickhouse-recorder
  variables:
    HELM_REGISTRY: registry.gitlab.com
    HELM_REGISTRY_PROJECT: gitlab-exporter/helm-charts
    # HELM_REGISTRY_USER:
    # HELM_REGISTRY_PASSWORD:
    HELM_CHART_DIR: deploy/helm/$APP

    HELM_PUSH: "0"
  script:
    - helm package "${HELM_CHART_DIR}" --destination .charts
    - |
      if [ "${HELM_PUSH}" == "1" ]; then
        echo "${HELM_REGISTRY_PASSWORD}" | helm registry login ${HELM_REGISTRY} --username ${HELM_REGISTRY_USER} --password-stdin
        helm push .charts/*.tgz oci://${HELM_REGISTRY}/${HELM_REGISTRY_PROJECT}
      fi

test:
  stage: test
  needs:
    - job: build
      artifacts: false
  cache:
    - <<: *cache-defaults
  script:
    - make test REPORTS=1
  after_script:
    - find reports/ -type f -name junit.xml | xargs go run go.cluttr.dev/junitxml/cmd/junitxml@latest merge -o reports/junit.xml
  artifacts:
    when: always
    paths:
      - reports/
    reports:
      junit: reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura-coverage.xml

release:
  stage: release
  dependencies: []
  rules:
    - if: $CI_COMMIT_TAG != null
  cache:
    - <<: *cache-defaults
  script:
    - make dist
    - .gitlab/release.sh
  artifacts:
    paths:
      - bin/linux_amd64
      - bin/linux_arm64

release-image:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG != null
  extends: build-image
  needs:
    - job: release
      artifacts: true
  variables:
    VERSION: $CI_COMMIT_TAG

    BUILDKIT_IMAGE: "$CI_REGISTRY/$IMAGE:$VERSION,$CI_REGISTRY/$IMAGE:latest"
    BUILDKIT_PUSH: "true"

release-chart:
  extends: build-chart
  stage: release
  rules:
    - if: $CI_COMMIT_TAG != null
      changes:
        paths:
          - deploy/helm/${APP}/Chart.yaml
        compare_to: $CI_DEFAULT_BRANCH
  needs:
    - job: release-image
      artifacts: false
  variables:
    HELM_PUSH: "1"
  artifacts:
    paths:
      - .charts/*.tgz

release-sync:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG != null
  needs:
    - job: release
      artifacts: false
  variables:
    GITHUB_OWNER: cluttrdev
    GITHUB_REPO: gitlab-exporter
  script:
    - | # Trigger GitHub release sync workflow
      curl \
        -sSL --fail-with-body \
        --header "Accept: application/vnd.github.v3+json" \
        --header "Authorization: Bearer ${GITHUB_TOKEN}" \
        --data "{\"ref\":\"${CI_COMMIT_TAG}\"}" \
        "https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/actions/workflows/release.yml/dispatches"

