{
 "title": "Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(process_start_time_seconds,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"$job\"},instance)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"^($job)$\",instance=~\"^($instance)$\"}",
     "legendFormat": "{{instance}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=~\"^($job)$\",instance=~\"^($instance)$\"}",
     "legendFormat": "{{instance}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=~\"^($job)$\",instance=~\"^($instance)$\"}[$interval])",
     "legendFormat": "{{instance}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{job=~\"^($job)$\",instance=~\"^($instance)$\"}[$interval])",
     "legendFormat": "{{instance}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"^($job)$\",instance=~\"^($instance)$\"}",
     "legendFormat": "{{instance}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"^($job)$\",instance=~\"^($instance)$\"}[30s])",
     "legendFormat": "{{instance}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"^($job)$\",instance=~\"^($instance)$\"}",
     "legendFormat": "{{instance}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"^($job)$\",instance=~\"^($instance)$\"}",
     "legendFormat": "{{instance}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{job=~\"^($job)$\",instance=~\"^($instance)$\"}[$interval])",
     "legendFormat": "{{instance}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"^($job)$\",instance=~\"^($instance)$\"}[$interval])",
     "legendFormat": "{{instance}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{job=~\"^($job)$\",instance=~\"^($instance)$\"}[$interval])",
     "legendFormat": "{{instance}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{job=~\"^($job)$\",instance=~\"^($instance)$\"}[$interval])",
     "legendFormat": "{{instance}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"^($job)$\",instance=~\"^($instance)$\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{job=~\"^($job)$\",instance=~\"^($instance)$\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"^($job)$\",instance=~\"^($instance)$\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"^($job)$\",instance=~\"^($instance)$\"}",
     "legendFormat": "{{instance}}: {{quantile}}"
    }
   ]
  }
 ]
}