{{- if (and .Values.monitoring.enabled .Values.config.http.enabled ) }}

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "gitlab-exporter.fullname" . }}
  labels:
    {{- include "gitlab-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gitlab-exporter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: http
      path: {{ .Values.monitoring.path | quote }}
      interval: {{ .Values.monitoring.interval | quote }} 

{{- end }}

