// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.30.2
// source: gitlabexporter/protobuf/commit.proto

package typespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Commit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortId        string                 `protobuf:"bytes,2,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	ParentIds      []string               `protobuf:"bytes,3,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	ProjectId      int64                  `protobuf:"varint,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AuthorName     string                 `protobuf:"bytes,5,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorEmail    string                 `protobuf:"bytes,6,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	AuthoredDate   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=authored_date,json=authoredDate,proto3" json:"authored_date,omitempty"`
	CommitterName  string                 `protobuf:"bytes,8,opt,name=committer_name,json=committerName,proto3" json:"committer_name,omitempty"`
	CommitterEmail string                 `protobuf:"bytes,9,opt,name=committer_email,json=committerEmail,proto3" json:"committer_email,omitempty"`
	CommittedDate  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=committed_date,json=committedDate,proto3" json:"committed_date,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Title          string                 `protobuf:"bytes,12,opt,name=title,proto3" json:"title,omitempty"`
	Message        string                 `protobuf:"bytes,13,opt,name=message,proto3" json:"message,omitempty"`
	Trailers       map[string]string      `protobuf:"bytes,14,rep,name=trailers,proto3" json:"trailers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Stats          *CommitStats           `protobuf:"bytes,15,opt,name=stats,proto3" json:"stats,omitempty"`
	Status         string                 `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	WebUrl         string                 `protobuf:"bytes,17,opt,name=web_url,json=webUrl,proto3" json:"web_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_gitlabexporter_protobuf_commit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_commit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_commit_proto_rawDescGZIP(), []int{0}
}

func (x *Commit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Commit) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

func (x *Commit) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *Commit) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Commit) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *Commit) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *Commit) GetAuthoredDate() *timestamppb.Timestamp {
	if x != nil {
		return x.AuthoredDate
	}
	return nil
}

func (x *Commit) GetCommitterName() string {
	if x != nil {
		return x.CommitterName
	}
	return ""
}

func (x *Commit) GetCommitterEmail() string {
	if x != nil {
		return x.CommitterEmail
	}
	return ""
}

func (x *Commit) GetCommittedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedDate
	}
	return nil
}

func (x *Commit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Commit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Commit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Commit) GetTrailers() map[string]string {
	if x != nil {
		return x.Trailers
	}
	return nil
}

func (x *Commit) GetStats() *CommitStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Commit) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Commit) GetWebUrl() string {
	if x != nil {
		return x.WebUrl
	}
	return ""
}

type CommitStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Additions     int64                  `protobuf:"varint,1,opt,name=additions,proto3" json:"additions,omitempty"`
	Deletions     int64                  `protobuf:"varint,2,opt,name=deletions,proto3" json:"deletions,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitStats) Reset() {
	*x = CommitStats{}
	mi := &file_gitlabexporter_protobuf_commit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitStats) ProtoMessage() {}

func (x *CommitStats) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_commit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitStats.ProtoReflect.Descriptor instead.
func (*CommitStats) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_commit_proto_rawDescGZIP(), []int{1}
}

func (x *CommitStats) GetAdditions() int64 {
	if x != nil {
		return x.Additions
	}
	return 0
}

func (x *CommitStats) GetDeletions() int64 {
	if x != nil {
		return x.Deletions
	}
	return 0
}

func (x *CommitStats) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_gitlabexporter_protobuf_commit_proto protoreflect.FileDescriptor

const file_gitlabexporter_protobuf_commit_proto_rawDesc = "" +
	"\n" +
	"$gitlabexporter/protobuf/commit.proto\x12\x17gitlabexporter.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x05\n" +
	"\x06Commit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bshort_id\x18\x02 \x01(\tR\ashortId\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x03 \x03(\tR\tparentIds\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\x03R\tprojectId\x12\x1f\n" +
	"\vauthor_name\x18\x05 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fauthor_email\x18\x06 \x01(\tR\vauthorEmail\x12?\n" +
	"\rauthored_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fauthoredDate\x12%\n" +
	"\x0ecommitter_name\x18\b \x01(\tR\rcommitterName\x12'\n" +
	"\x0fcommitter_email\x18\t \x01(\tR\x0ecommitterEmail\x12A\n" +
	"\x0ecommitted_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rcommittedDate\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05title\x18\f \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\r \x01(\tR\amessage\x12I\n" +
	"\btrailers\x18\x0e \x03(\v2-.gitlabexporter.protobuf.Commit.TrailersEntryR\btrailers\x12:\n" +
	"\x05stats\x18\x0f \x01(\v2$.gitlabexporter.protobuf.CommitStatsR\x05stats\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x12\x17\n" +
	"\aweb_url\x18\x11 \x01(\tR\x06webUrl\x1a;\n" +
	"\rTrailersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\vCommitStats\x12\x1c\n" +
	"\tadditions\x18\x01 \x01(\x03R\tadditions\x12\x1c\n" +
	"\tdeletions\x18\x02 \x01(\x03R\tdeletions\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05totalB0Z.go.cluttr.dev/gitlab-exporter/protobuf/typespbb\x06proto3"

var (
	file_gitlabexporter_protobuf_commit_proto_rawDescOnce sync.Once
	file_gitlabexporter_protobuf_commit_proto_rawDescData []byte
)

func file_gitlabexporter_protobuf_commit_proto_rawDescGZIP() []byte {
	file_gitlabexporter_protobuf_commit_proto_rawDescOnce.Do(func() {
		file_gitlabexporter_protobuf_commit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gitlabexporter_protobuf_commit_proto_rawDesc), len(file_gitlabexporter_protobuf_commit_proto_rawDesc)))
	})
	return file_gitlabexporter_protobuf_commit_proto_rawDescData
}

var file_gitlabexporter_protobuf_commit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gitlabexporter_protobuf_commit_proto_goTypes = []any{
	(*Commit)(nil),                // 0: gitlabexporter.protobuf.Commit
	(*CommitStats)(nil),           // 1: gitlabexporter.protobuf.CommitStats
	nil,                           // 2: gitlabexporter.protobuf.Commit.TrailersEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_gitlabexporter_protobuf_commit_proto_depIdxs = []int32{
	3, // 0: gitlabexporter.protobuf.Commit.authored_date:type_name -> google.protobuf.Timestamp
	3, // 1: gitlabexporter.protobuf.Commit.committed_date:type_name -> google.protobuf.Timestamp
	3, // 2: gitlabexporter.protobuf.Commit.created_at:type_name -> google.protobuf.Timestamp
	2, // 3: gitlabexporter.protobuf.Commit.trailers:type_name -> gitlabexporter.protobuf.Commit.TrailersEntry
	1, // 4: gitlabexporter.protobuf.Commit.stats:type_name -> gitlabexporter.protobuf.CommitStats
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gitlabexporter_protobuf_commit_proto_init() }
func file_gitlabexporter_protobuf_commit_proto_init() {
	if File_gitlabexporter_protobuf_commit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gitlabexporter_protobuf_commit_proto_rawDesc), len(file_gitlabexporter_protobuf_commit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gitlabexporter_protobuf_commit_proto_goTypes,
		DependencyIndexes: file_gitlabexporter_protobuf_commit_proto_depIdxs,
		MessageInfos:      file_gitlabexporter_protobuf_commit_proto_msgTypes,
	}.Build()
	File_gitlabexporter_protobuf_commit_proto = out.File
	file_gitlabexporter_protobuf_commit_proto_goTypes = nil
	file_gitlabexporter_protobuf_commit_proto_depIdxs = nil
}
