// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: gitlabexporter/protobuf/references.proto

package typespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploymentTier int32

const (
	DeploymentTier_DEPLOYMENT_TIER_UNSPECIFIED DeploymentTier = 0
	DeploymentTier_DEPLOYMENT_TIER_PRODUCTION  DeploymentTier = 1
	DeploymentTier_DEPLOYMENT_TIER_STAGING     DeploymentTier = 2
	DeploymentTier_DEPLOYMENT_TIER_TESTING     DeploymentTier = 3
	DeploymentTier_DEPLOYMENT_TIER_DEVELOPMENT DeploymentTier = 4
	DeploymentTier_DEPLOYMENT_TIER_OTHER       DeploymentTier = 5
)

// Enum value maps for DeploymentTier.
var (
	DeploymentTier_name = map[int32]string{
		0: "DEPLOYMENT_TIER_UNSPECIFIED",
		1: "DEPLOYMENT_TIER_PRODUCTION",
		2: "DEPLOYMENT_TIER_STAGING",
		3: "DEPLOYMENT_TIER_TESTING",
		4: "DEPLOYMENT_TIER_DEVELOPMENT",
		5: "DEPLOYMENT_TIER_OTHER",
	}
	DeploymentTier_value = map[string]int32{
		"DEPLOYMENT_TIER_UNSPECIFIED": 0,
		"DEPLOYMENT_TIER_PRODUCTION":  1,
		"DEPLOYMENT_TIER_STAGING":     2,
		"DEPLOYMENT_TIER_TESTING":     3,
		"DEPLOYMENT_TIER_DEVELOPMENT": 4,
		"DEPLOYMENT_TIER_OTHER":       5,
	}
)

func (x DeploymentTier) Enum() *DeploymentTier {
	p := new(DeploymentTier)
	*p = x
	return p
}

func (x DeploymentTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentTier) Descriptor() protoreflect.EnumDescriptor {
	return file_gitlabexporter_protobuf_references_proto_enumTypes[0].Descriptor()
}

func (DeploymentTier) Type() protoreflect.EnumType {
	return &file_gitlabexporter_protobuf_references_proto_enumTypes[0]
}

func (x DeploymentTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentTier.Descriptor instead.
func (DeploymentTier) EnumDescriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_references_proto_rawDescGZIP(), []int{0}
}

type NamespaceReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullPath string `protobuf:"bytes,2,opt,name=full_path,json=fullPath,proto3" json:"full_path,omitempty"`
}

func (x *NamespaceReference) Reset() {
	*x = NamespaceReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespaceReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceReference) ProtoMessage() {}

func (x *NamespaceReference) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceReference.ProtoReflect.Descriptor instead.
func (*NamespaceReference) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_references_proto_rawDescGZIP(), []int{0}
}

func (x *NamespaceReference) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NamespaceReference) GetFullPath() string {
	if x != nil {
		return x.FullPath
	}
	return ""
}

type ProjectReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullPath  string              `protobuf:"bytes,2,opt,name=full_path,json=fullPath,proto3" json:"full_path,omitempty"`
	Namespace *NamespaceReference `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *ProjectReference) Reset() {
	*x = ProjectReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectReference) ProtoMessage() {}

func (x *ProjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectReference.ProtoReflect.Descriptor instead.
func (*ProjectReference) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_references_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectReference) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectReference) GetFullPath() string {
	if x != nil {
		return x.FullPath
	}
	return ""
}

func (x *ProjectReference) GetNamespace() *NamespaceReference {
	if x != nil {
		return x.Namespace
	}
	return nil
}

type PipelineReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Iid     int64             `protobuf:"varint,2,opt,name=iid,proto3" json:"iid,omitempty"`
	Project *ProjectReference `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
}

func (x *PipelineReference) Reset() {
	*x = PipelineReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineReference) ProtoMessage() {}

func (x *PipelineReference) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineReference.ProtoReflect.Descriptor instead.
func (*PipelineReference) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_references_proto_rawDescGZIP(), []int{2}
}

func (x *PipelineReference) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PipelineReference) GetIid() int64 {
	if x != nil {
		return x.Iid
	}
	return 0
}

func (x *PipelineReference) GetProject() *ProjectReference {
	if x != nil {
		return x.Project
	}
	return nil
}

type JobReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pipeline *PipelineReference `protobuf:"bytes,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
}

func (x *JobReference) Reset() {
	*x = JobReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobReference) ProtoMessage() {}

func (x *JobReference) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobReference.ProtoReflect.Descriptor instead.
func (*JobReference) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_references_proto_rawDescGZIP(), []int{3}
}

func (x *JobReference) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobReference) GetPipeline() *PipelineReference {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type TestReportReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Job *JobReference `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *TestReportReference) Reset() {
	*x = TestReportReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestReportReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestReportReference) ProtoMessage() {}

func (x *TestReportReference) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestReportReference.ProtoReflect.Descriptor instead.
func (*TestReportReference) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_references_proto_rawDescGZIP(), []int{4}
}

func (x *TestReportReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestReportReference) GetJob() *JobReference {
	if x != nil {
		return x.Job
	}
	return nil
}

type TestSuiteReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TestReport *TestReportReference `protobuf:"bytes,3,opt,name=test_report,json=testReport,proto3" json:"test_report,omitempty"`
}

func (x *TestSuiteReference) Reset() {
	*x = TestSuiteReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestSuiteReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSuiteReference) ProtoMessage() {}

func (x *TestSuiteReference) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSuiteReference.ProtoReflect.Descriptor instead.
func (*TestSuiteReference) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_references_proto_rawDescGZIP(), []int{5}
}

func (x *TestSuiteReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestSuiteReference) GetTestReport() *TestReportReference {
	if x != nil {
		return x.TestReport
	}
	return nil
}

type RunnerReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RunnerReference) Reset() {
	*x = RunnerReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunnerReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerReference) ProtoMessage() {}

func (x *RunnerReference) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerReference.ProtoReflect.Descriptor instead.
func (*RunnerReference) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_references_proto_rawDescGZIP(), []int{6}
}

func (x *RunnerReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MergeRequestReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Iid     int64             `protobuf:"varint,2,opt,name=iid,proto3" json:"iid,omitempty"`
	Project *ProjectReference `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
}

func (x *MergeRequestReference) Reset() {
	*x = MergeRequestReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeRequestReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequestReference) ProtoMessage() {}

func (x *MergeRequestReference) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequestReference.ProtoReflect.Descriptor instead.
func (*MergeRequestReference) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_references_proto_rawDescGZIP(), []int{7}
}

func (x *MergeRequestReference) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MergeRequestReference) GetIid() int64 {
	if x != nil {
		return x.Iid
	}
	return 0
}

func (x *MergeRequestReference) GetProject() *ProjectReference {
	if x != nil {
		return x.Project
	}
	return nil
}

type MilestoneReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Iid     int64             `protobuf:"varint,2,opt,name=iid,proto3" json:"iid,omitempty"`
	Project *ProjectReference `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
}

func (x *MilestoneReference) Reset() {
	*x = MilestoneReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MilestoneReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilestoneReference) ProtoMessage() {}

func (x *MilestoneReference) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilestoneReference.ProtoReflect.Descriptor instead.
func (*MilestoneReference) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_references_proto_rawDescGZIP(), []int{8}
}

func (x *MilestoneReference) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MilestoneReference) GetIid() int64 {
	if x != nil {
		return x.Iid
	}
	return 0
}

func (x *MilestoneReference) GetProject() *ProjectReference {
	if x != nil {
		return x.Project
	}
	return nil
}

type UserReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserReference) Reset() {
	*x = UserReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReference) ProtoMessage() {}

func (x *UserReference) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReference.ProtoReflect.Descriptor instead.
func (*UserReference) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_references_proto_rawDescGZIP(), []int{9}
}

func (x *UserReference) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserReference) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnvironmentReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tier    DeploymentTier    `protobuf:"varint,3,opt,name=tier,proto3,enum=gitlabexporter.protobuf.DeploymentTier" json:"tier,omitempty"`
	Project *ProjectReference `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
}

func (x *EnvironmentReference) Reset() {
	*x = EnvironmentReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvironmentReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentReference) ProtoMessage() {}

func (x *EnvironmentReference) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_references_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentReference.ProtoReflect.Descriptor instead.
func (*EnvironmentReference) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_references_proto_rawDescGZIP(), []int{10}
}

func (x *EnvironmentReference) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnvironmentReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvironmentReference) GetTier() DeploymentTier {
	if x != nil {
		return x.Tier
	}
	return DeploymentTier_DEPLOYMENT_TIER_UNSPECIFIED
}

func (x *EnvironmentReference) GetProject() *ProjectReference {
	if x != nil {
		return x.Project
	}
	return nil
}

var File_gitlabexporter_protobuf_references_proto protoreflect.FileDescriptor

var file_gitlabexporter_protobuf_references_proto_rawDesc = []byte{
	0x0a, 0x28, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x67, 0x69, 0x74, 0x6c,
	0x61, 0x62, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x22, 0x41, 0x0a, 0x12, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c,
	0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75,
	0x6c, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x22, 0x8a, 0x01, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x75, 0x6c, 0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x75, 0x6c, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x49, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x67, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x22, 0x7a, 0x0a, 0x11, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x69, 0x69, 0x64, 0x12, 0x43, 0x0a, 0x07, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x67, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x22,
	0x7a, 0x0a, 0x0c, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x46, 0x0a, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x65, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x5e, 0x0a, 0x13, 0x54,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x37, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x22, 0x73, 0x0a, 0x12, 0x54,
	0x65, 0x73, 0x74, 0x53, 0x75, 0x69, 0x74, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x4d, 0x0a, 0x0b, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x65,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x52, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x22, 0x21, 0x0a, 0x0f, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x7e, 0x0a, 0x15, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x69, 0x69, 0x64, 0x12, 0x43,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x29, 0x2e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x22, 0x7b, 0x0a, 0x12, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x69, 0x69, 0x64, 0x12, 0x43, 0x0a, 0x07, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x67,
	0x69, 0x74, 0x6c, 0x61, 0x62, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x22, 0x4f, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0xbc, 0x01, 0x0a, 0x14, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b,
	0x0a, 0x04, 0x74, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x67,
	0x69, 0x74, 0x6c, 0x61, 0x62, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x69, 0x65, 0x72, 0x52, 0x04, 0x74, 0x69, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x07, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x67,
	0x69, 0x74, 0x6c, 0x61, 0x62, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x2a, 0xc7, 0x01, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54,
	0x69, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x1b, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x4d, 0x45, 0x4e,
	0x54, 0x5f, 0x54, 0x49, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x4d, 0x45,
	0x4e, 0x54, 0x5f, 0x54, 0x49, 0x45, 0x52, 0x5f, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x4d, 0x45,
	0x4e, 0x54, 0x5f, 0x54, 0x49, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x47, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f,
	0x54, 0x49, 0x45, 0x52, 0x5f, 0x54, 0x45, 0x53, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x1f,
	0x0a, 0x1b, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x49, 0x45,
	0x52, 0x5f, 0x44, 0x45, 0x56, 0x45, 0x4c, 0x4f, 0x50, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x04, 0x12,
	0x19, 0x0a, 0x15, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x49,
	0x45, 0x52, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x05, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x75, 0x74, 0x74, 0x72, 0x64,
	0x65, 0x76, 0x2f, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2d, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gitlabexporter_protobuf_references_proto_rawDescOnce sync.Once
	file_gitlabexporter_protobuf_references_proto_rawDescData = file_gitlabexporter_protobuf_references_proto_rawDesc
)

func file_gitlabexporter_protobuf_references_proto_rawDescGZIP() []byte {
	file_gitlabexporter_protobuf_references_proto_rawDescOnce.Do(func() {
		file_gitlabexporter_protobuf_references_proto_rawDescData = protoimpl.X.CompressGZIP(file_gitlabexporter_protobuf_references_proto_rawDescData)
	})
	return file_gitlabexporter_protobuf_references_proto_rawDescData
}

var file_gitlabexporter_protobuf_references_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gitlabexporter_protobuf_references_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gitlabexporter_protobuf_references_proto_goTypes = []interface{}{
	(DeploymentTier)(0),           // 0: gitlabexporter.protobuf.DeploymentTier
	(*NamespaceReference)(nil),    // 1: gitlabexporter.protobuf.NamespaceReference
	(*ProjectReference)(nil),      // 2: gitlabexporter.protobuf.ProjectReference
	(*PipelineReference)(nil),     // 3: gitlabexporter.protobuf.PipelineReference
	(*JobReference)(nil),          // 4: gitlabexporter.protobuf.JobReference
	(*TestReportReference)(nil),   // 5: gitlabexporter.protobuf.TestReportReference
	(*TestSuiteReference)(nil),    // 6: gitlabexporter.protobuf.TestSuiteReference
	(*RunnerReference)(nil),       // 7: gitlabexporter.protobuf.RunnerReference
	(*MergeRequestReference)(nil), // 8: gitlabexporter.protobuf.MergeRequestReference
	(*MilestoneReference)(nil),    // 9: gitlabexporter.protobuf.MilestoneReference
	(*UserReference)(nil),         // 10: gitlabexporter.protobuf.UserReference
	(*EnvironmentReference)(nil),  // 11: gitlabexporter.protobuf.EnvironmentReference
}
var file_gitlabexporter_protobuf_references_proto_depIdxs = []int32{
	1, // 0: gitlabexporter.protobuf.ProjectReference.namespace:type_name -> gitlabexporter.protobuf.NamespaceReference
	2, // 1: gitlabexporter.protobuf.PipelineReference.project:type_name -> gitlabexporter.protobuf.ProjectReference
	3, // 2: gitlabexporter.protobuf.JobReference.pipeline:type_name -> gitlabexporter.protobuf.PipelineReference
	4, // 3: gitlabexporter.protobuf.TestReportReference.job:type_name -> gitlabexporter.protobuf.JobReference
	5, // 4: gitlabexporter.protobuf.TestSuiteReference.test_report:type_name -> gitlabexporter.protobuf.TestReportReference
	2, // 5: gitlabexporter.protobuf.MergeRequestReference.project:type_name -> gitlabexporter.protobuf.ProjectReference
	2, // 6: gitlabexporter.protobuf.MilestoneReference.project:type_name -> gitlabexporter.protobuf.ProjectReference
	0, // 7: gitlabexporter.protobuf.EnvironmentReference.tier:type_name -> gitlabexporter.protobuf.DeploymentTier
	2, // 8: gitlabexporter.protobuf.EnvironmentReference.project:type_name -> gitlabexporter.protobuf.ProjectReference
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_gitlabexporter_protobuf_references_proto_init() }
func file_gitlabexporter_protobuf_references_proto_init() {
	if File_gitlabexporter_protobuf_references_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gitlabexporter_protobuf_references_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamespaceReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlabexporter_protobuf_references_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlabexporter_protobuf_references_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlabexporter_protobuf_references_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlabexporter_protobuf_references_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestReportReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlabexporter_protobuf_references_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestSuiteReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlabexporter_protobuf_references_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunnerReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlabexporter_protobuf_references_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeRequestReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlabexporter_protobuf_references_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MilestoneReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlabexporter_protobuf_references_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlabexporter_protobuf_references_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvironmentReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gitlabexporter_protobuf_references_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gitlabexporter_protobuf_references_proto_goTypes,
		DependencyIndexes: file_gitlabexporter_protobuf_references_proto_depIdxs,
		EnumInfos:         file_gitlabexporter_protobuf_references_proto_enumTypes,
		MessageInfos:      file_gitlabexporter_protobuf_references_proto_msgTypes,
	}.Build()
	File_gitlabexporter_protobuf_references_proto = out.File
	file_gitlabexporter_protobuf_references_proto_rawDesc = nil
	file_gitlabexporter_protobuf_references_proto_goTypes = nil
	file_gitlabexporter_protobuf_references_proto_depIdxs = nil
}
