// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.30.2
// source: gitlabexporter/protobuf/section.proto

package typespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Job           *JobReference          `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,12,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_gitlabexporter_protobuf_section_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_gitlabexporter_protobuf_section_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_gitlabexporter_protobuf_section_proto_rawDescGZIP(), []int{0}
}

func (x *Section) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Section) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Section) GetJob() *JobReference {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *Section) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Section) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Section) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

var File_gitlabexporter_protobuf_section_proto protoreflect.FileDescriptor

const file_gitlabexporter_protobuf_section_proto_rawDesc = "" +
	"\n" +
	"%gitlabexporter/protobuf/section.proto\x12\x17gitlabexporter.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a(gitlabexporter/protobuf/references.proto\"\x95\x02\n" +
	"\aSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\x03job\x18\x03 \x01(\v2%.gitlabexporter.protobuf.JobReferenceR\x03job\x129\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x125\n" +
	"\bduration\x18\f \x01(\v2\x19.google.protobuf.DurationR\bdurationB0Z.go.cluttr.dev/gitlab-exporter/protobuf/typespbb\x06proto3"

var (
	file_gitlabexporter_protobuf_section_proto_rawDescOnce sync.Once
	file_gitlabexporter_protobuf_section_proto_rawDescData []byte
)

func file_gitlabexporter_protobuf_section_proto_rawDescGZIP() []byte {
	file_gitlabexporter_protobuf_section_proto_rawDescOnce.Do(func() {
		file_gitlabexporter_protobuf_section_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gitlabexporter_protobuf_section_proto_rawDesc), len(file_gitlabexporter_protobuf_section_proto_rawDesc)))
	})
	return file_gitlabexporter_protobuf_section_proto_rawDescData
}

var file_gitlabexporter_protobuf_section_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gitlabexporter_protobuf_section_proto_goTypes = []any{
	(*Section)(nil),               // 0: gitlabexporter.protobuf.Section
	(*JobReference)(nil),          // 1: gitlabexporter.protobuf.JobReference
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 3: google.protobuf.Duration
}
var file_gitlabexporter_protobuf_section_proto_depIdxs = []int32{
	1, // 0: gitlabexporter.protobuf.Section.job:type_name -> gitlabexporter.protobuf.JobReference
	2, // 1: gitlabexporter.protobuf.Section.started_at:type_name -> google.protobuf.Timestamp
	2, // 2: gitlabexporter.protobuf.Section.finished_at:type_name -> google.protobuf.Timestamp
	3, // 3: gitlabexporter.protobuf.Section.duration:type_name -> google.protobuf.Duration
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gitlabexporter_protobuf_section_proto_init() }
func file_gitlabexporter_protobuf_section_proto_init() {
	if File_gitlabexporter_protobuf_section_proto != nil {
		return
	}
	file_gitlabexporter_protobuf_references_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gitlabexporter_protobuf_section_proto_rawDesc), len(file_gitlabexporter_protobuf_section_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gitlabexporter_protobuf_section_proto_goTypes,
		DependencyIndexes: file_gitlabexporter_protobuf_section_proto_depIdxs,
		MessageInfos:      file_gitlabexporter_protobuf_section_proto_msgTypes,
	}.Build()
	File_gitlabexporter_protobuf_section_proto = out.File
	file_gitlabexporter_protobuf_section_proto_goTypes = nil
	file_gitlabexporter_protobuf_section_proto_depIdxs = nil
}
