# GitLab API client settings
gitlab:
  # Base URL of the GitLab instance.
  url: "https://gitlab.com"
  # Token to use for authenticating against the GitLab API.
  # Only requires `read-api` permissions.
  token: ""

  # GitLab OAuth2 flow options
  oauth:
    # The authorization code flow application's id.
    client_id: ""
    # The authorization code flow application's secret.
    client_secret: ""

    # The password credentials flow username.
    username: ""
    # The password credentials flow password.
    password: ""

    # The file to read the secrets from if not read from config file.
    secrets_file: ""

    # The flow type to use for authentication.
    flow_type: ""

  client:
    rate:
      limit: 0.0

# List of gRPC server endpoints to export to
endpoints: []
  # - address: "127.0.0.1:36275"

# Default settings for projects
project_defaults:
  export:
    sections:
      # Whether or not to export job section data.
      # If enabled, this may significantly increase the export time since it
      # requires fetching entire job logs to parse for section information.
      enabled: true
    
    testreports:
      # Whether or not to export pipeline testreports.
      enabled: true

    reports:
      # Whether to export data from report artifacts.
      enabled: false

      junit:
        # Whether to export unit test report data.
        enabled: false
    
    traces:
      # Whether or not to export pipeline hierarchies as traces.
      enabled: true
  
    metrics:
      # Whether or not to export metrics embedded in job logs.
      # If enabled, this may significantly increase the export time since it
      # requires fetching entire job logs to parse for embedded metrics.
      enabled: true

    mergerequests:
      # Whether or not to export merge request data.
      enabled: true

      note_events: true
  
  catch_up:
    # Whether to export data from past pipelines at startup.
    # This is ignored when using the `run` command, unless the `--catchup` flag is set.
    enabled: false
  
    # Export pipelines updated after the specified date.
    # Expected in ISO 8601 format (2019-03-15T08:00:00Z)
    updated_after: ""
  
    # Export pipelines updated before the specified date.
    # Expected in ISO 8601 format (2019-03-15T08:00:00Z)
    updated_before: ""
  

# List of projects to export
projects: []
  # - # Project ID project (required).
  #   id: 50817395  # cluttrdev/gitlab-exporter
  #   
  #   # See `project_defaults` for settings that can be overwritten here.
  #   export: {}
  #   catch_up: {}

# List of namespaces of which to export projects
namespaces: []
  # - # The namespace id or url-encoded path
  #   id: gitlab-exporter
  #
  #   # The namespace kind (user or group).
  #   # Optional, will be determined if not specified.
  #   kind: group
  #
  #   # Limit by visibility (public, internal or private)
  #   visibility: ""
  #
  #   # Include projects shared to this group.
  #   # (Only applicable for group namespaces)
  #   with_shared: false
  #
  #   # Whether to include projects in subgroups of this namespace.
  #   # (Only applicable for group namespaces)
  #   include_subgroups: false
  #
  #   # See `project_defaults` for settings that can be overwritten here.
  #   export: {}
  #   catch_up: {}

# HTTP server settings
http:
  # Whether to enable serving http endpoint (metrics, debug info)
  enabled: true
  # The host part of the server address
  host: "127.0.0.1"
  # The port the server listens on
  port: "9100"
  # Whether to enable debug endpoints
  debug: false

# Log configuration
log:
  # The logging level
  # allowed values: debug, info, warning, error
  level: info

  # The logging format
  # allowed values: text or json
  format: text
