# GitLab API client settings
gitlab:
  # Base URL of the GitLab instance.
  url: "https://gitlab.com"
  # Token to use for authenticating against the GitLab API.
  # Only requires `read-api` permissions.
  token: ""

  # The username to use for http session authentication.
  # (only required if exporting report artifacts is enabled)
  username: ""
  # The password to use for http session authentication.
  # (only required if exporting report artifacts is enabled)
  password: ""

  client:
    rate:
      limit: 0.0

# List of gRPC server endpoints to export to
endpoints: []
  # - address: "127.0.0.1:36275"

# Default settings for projects
project_defaults:
  export:
    deployments:
      # Whether to export deployments data.
      enabled: true

    metrics:
      # Whether or not to export metrics embedded in job logs.
      # If enabled, this may significantly increase the export time since it
      # requires fetching entire job logs.
      enabled: true

    mergerequests:
      # Whether or not to export merge request data.
      enabled: true

      note_events: true

    reports:
      # Whether to export data from report artifacts.
      enabled: false

      junit:
        # Whether to export unit test report data.
        enabled: false
        # Paths to files inside the artifacts archives.
        # Optional, if not set it will try to donwload the report from a
        # non-API endpoint (requires experimental authed http client).
        paths: []

      coverage:
        # Whether to export test coverage data.
        # (Currently, only cobertura report format is supported)
        enabled: false
        # Paths to files inside the artifacts archives.
        # Optional, if not set it will try to donwload the report from a
        # non-API endpoint (experimental, requires authed http client).
        paths: []
    
    sections:
      # Whether or not to export job section data.
      # If enabled, this may significantly increase the export time since it
      # requires fetching entire job logs.
      enabled: true

    jobs:
      properties:
        # Whether or not to export properties embedded in job logs.
        # If enabled, this may significantly increase the export time since it
        # requires fetching entire job logs.
        enabled: true

    testreports:
      # Whether or not to export pipeline testreports.
      enabled: true

    traces:
      # Whether or not to export pipeline hierarchies as traces.
      enabled: true
  
  catch_up:
    # Whether to export data from past pipelines at startup.
    # This is ignored when using the `run` command, unless the `--catchup` flag is set.
    enabled: false
  
    # Export pipelines updated after the specified date.
    # Expected in ISO 8601 format (2019-03-15T08:00:00Z)
    updated_after: ""
  
    # Export pipelines updated before the specified date.
    # Expected in ISO 8601 format (2019-03-15T08:00:00Z)
    updated_before: ""
  

# List of projects to export
projects: []
  # - # Project ID project (required).
  #   id: 50817395  # akun73/gitlab-exporter
  #   
  #   # See `project_defaults` for settings that can be overwritten here.
  #   export: {}
  #   catch_up: {}

# List of namespaces of which to export projects
namespaces: []
  # - # The namespace id or url-encoded path
  #   id: gitlab-exporter
  #
  #   # The namespace kind (user or group).
  #   # Optional, will be determined if not specified.
  #   kind: group
  #
  #   # Limit by visibility (public, internal or private)
  #   visibility: ""
  #
  #   # Include projects shared to this group.
  #   # (Only applicable for group namespaces)
  #   with_shared: false
  #
  #   # Whether to include projects in subgroups of this namespace.
  #   # (Only applicable for group namespaces)
  #   include_subgroups: false
  #
  #   # See `project_defaults` for settings that can be overwritten here.
  #   export: {}
  #   catch_up: {}

# HTTP server settings
http:
  # Whether to enable serving http endpoint (metrics, debug info)
  enabled: true
  # The host part of the server address
  host: "127.0.0.1"
  # The port the server listens on
  port: "9100"
  # Whether to enable debug endpoints
  debug: false

# Log configuration
log:
  # The logging level
  # allowed values: debug, info, warning, error
  level: info

  # The logging format
  # allowed values: text or json
  format: text
