apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab-clickhouse-exporter.fullname" . }}
  labels:
    {{- include "gitlab-clickhouse-exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gitlab-clickhouse-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gitlab-clickhouse-exporter.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gitlab-clickhouse-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
              {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
              - name: config
                mountPath: /etc/gitlab-clickhouse-exporter/
          ports:
            - name: http
              {{- $serverConfig := .Values.config.server | default dict }}
              containerPort: {{ $serverConfig.port | default "8080" }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: http
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: http
          env: 
              {{- toYaml .Values.env | nindent 12 }}
          args: ["run", "--config", "/etc/gitlab-clickhouse-exporter/config.yaml"]
      volumes:
        - name: config
          configMap:
            name: {{ include "gitlab-clickhouse-exporter.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

