name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: write  # allow creating a release
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Sync release
        env:
          TAG_NAME: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/release.sh
